struct A {
  float a;
  float b;
  float c;
  float d;
  float e;
  float f;
  float g;
  float h;
};

struct ZeroCopyMessage {
  unsigned long index;
  unsigned long long time;
  char message[64];
  A a[30];
};
